name: WPF CI/CD

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SmartEstimateApp.sln
        working-directory: SmartEstimateApp

      - name: Build
        run: dotnet build SmartEstimateApp.sln --configuration Release --no-restore
        working-directory: SmartEstimateApp

      - name: Run tests
        run: dotnet test SmartEstimateApp.sln --no-restore --verbosity normal
        working-directory: SmartEstimateApp

      - name: Publish
        run: dotnet publish SmartEstimateApp.csproj -c Release -o ../publish
        working-directory: SmartEstimateApp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WPFApp
          path: ./publish