on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            if (!/^feature|fix|docs/i.test(title)) {
              core.setFailed('PR title must start with feature, fix, or docs');
            }
